module.exports = {
  apps: [
    {
      name: 'shkola-pk-frontend',
      cwd: '/var/www/shkola-pk/app',
      script: 'node_modules/.bin/next',
      args: 'start',
      env: {
        PORT: 3000,
        NODE_ENV: 'production',
        NEXT_PUBLIC_APP_URL: 'https://2980738.ru',
        NEXT_PUBLIC_PAYLOAD_URL: 'https://2980738.ru',
        PAYLOAD_API_URL: 'http://localhost:3001',
        PAYLOAD_SECRET: 'sk-pk-2026-payload-secret-key-secure',
        DATABASE_URL: 'postgresql://shkola_pk:Shk0laPK2026!Db@localhost:5432/shkola_pk',
        JWT_SECRET: 'sk-pk-2026-veleslav-starkov-jwt-key-secure',
        YOOKASSA_SHOP_ID: 'test_shop_id',
        YOOKASSA_SECRET_KEY: 'test_secret_key',
        YOOKASSA_API_URL: 'https://api.yookassa.ru/v3',
        SMTP_HOST: 'smtp.mail.ru',
        SMTP_PORT: '587',
        SMTP_USER: 'boss@2980738.ru',
        SMTP_PASS: 'email_password_change_me',
        EMAIL_FROM: 'Школа ПК <boss@2980738.ru>',
      },
    },
    {
      name: 'shkola-pk-cms',
      cwd: '/var/www/shkola-pk/payload-cms',
      script: 'node_modules/.bin/next',
      args: 'start --port 3001',
      env: {
        PORT: 3001,
        NODE_ENV: 'production',
        DATABASE_URL: 'postgresql://shkola_pk:Shk0laPK2026!Db@localhost:5432/shkola_pk_payload',
        PAYLOAD_SECRET: 'sk-pk-2026-payload-secret-key-secure',
        NEXT_PUBLIC_APP_URL: 'https://2980738.ru',
        PAYLOAD_PUBLIC_SERVER_URL: 'https://2980738.ru',
        S3_ENDPOINT: '',
        S3_BUCKET: '',
        S3_ACCESS_KEY_ID: '',
        S3_SECRET_ACCESS_KEY: '',
        S3_REGION: 'ru-1',
      },
    },
  ],
};
